@page "/login"
@using DoctorAppWeb.Shared.Models
@using DoctorAppWeb.Client.Services
@layout AuthLayout
@inject NavigationManager navigationManager
@inject CustomStateProvider authStateProvider
    <br />
    <br />
    <br />
    <h2 class="loginTitle">
        Рабочее место врача на обходе
    </h2>
    <br />    
    <div class="authForm">
        <br />
        
        <br />

        <EditForm class="form-signin" OnValidSubmit="OnSubmit" Model="loginRequest">
            <DataAnnotationsValidator />
            <div class="loginData">
                <label for="inputUsername" class="sr-only">User Name</label>
                <InputText id="inputUsername" class="form-control" @bind-Value="loginRequest.UserName" autofocus placeholder="Username" />
                <ValidationMessage For="@(() => loginRequest.UserName)" />
                <br />
                <label for="inputPassword" class="sr-only">Password</label>
                <InputText type="password" id="inputPassword" class="form-control" placeholder="Password" @bind-Value="loginRequest.Password" />
                <ValidationMessage For="@(() => loginRequest.Password)" />
                <br />
                <div class="flexContainer">
                    <button class="btn btn-lg btn-primary" type="submit">Войти</button> <NavLink href="counter">Забыли пароль ?</NavLink>
                </div>
                <label class="text-danger">@error</label>
            </div>


            <br />
            <br />
            <br />
            <NavLink href="register">
                <h6 class="font-weight-normal text-center">Create account</h6>
            </NavLink>

        </EditForm>  
        
    </div>

    @code{
        LoginRequest loginRequest { get; set; } = new LoginRequest();
        string error { get; set; }


        async Task OnSubmit()
        {
            error = null;
            try
            {
                await authStateProvider.Login(loginRequest);
                navigationManager.NavigateTo("");
            }
            catch (Exception ex)
            {
                error = ex.Message;
            }
        }
    }